version: '3.7'
services:
  peer:
    container_name: peer
    restart: always
    image: ghcr.io/imperialcollegelondon/fabric-peer:bloccprotocol-release
    # FIXME: change core.yaml or CORE_PEER_ADDRESS to ignore this
    network_mode: host
    environment:
    - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
    - FABRIC_LOGGING_SPEC=INFO
    # NOTE: for BLOCC protocol
    - CORE_PEER_ADDRESS=${PEER_EXTERNAL_ENDPOINT}
    - CORE_PEER_LOCALMSPID=Container${FABRIC_CONTAINER_NUM}MSP
    # NOTE: server and client share the same cert and key
    - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
    - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
    - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    - CORE_PEER_PROFILE_ENABLED=false
    # Peer specific variables
    - CORE_PEER_FILESYSTEMPATH=/var/hyperledger/production
    - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
    - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
    volumes:
    - ~/fabric/config:/etc/hyperledger/peercfg
    - ~/fabric/organizations/peerOrganizations/container${FABRIC_CONTAINER_NUM}.blocc.doc.ic.ac.uk/peers/peer0.container${FABRIC_CONTAINER_NUM}.blocc.doc.ic.ac.uk:/etc/hyperledger/fabric
    - ~/fabric/peer0.container${FABRIC_CONTAINER_NUM}.blocc.doc.ic.ac.uk:/var/hyperledger/production
    - /var/run:/host/var/run
    working_dir: /root
    command: peer node start
    ports:
    - 7051:7051 # Peer listen port
    - 9444:9444 # Peer operation listen port

  orderer:
    container_name: orderer
    restart: always
    image: ghcr.io/imperialcollegelondon/fabric-orderer:bloccprotocol-release
    environment:
      - FABRIC_CFG_PATH=/var/hyperledger/config
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_ADMIN_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_ADMIN_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_TLS_CLIENTROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /root
    command: orderer
    volumes:
        - ~/fabric/config:/var/hyperledger/config
        - ~/fabric/organizations/ordererOrganizations/container${FABRIC_CONTAINER_NUM}.blocc.doc.ic.ac.uk/orderers/orderer.container${FABRIC_CONTAINER_NUM}.blocc.doc.ic.ac.uk/msp:/var/hyperledger/orderer/msp
        - ~/fabric/organizations/ordererOrganizations/container${FABRIC_CONTAINER_NUM}.blocc.doc.ic.ac.uk/orderers/orderer.container${FABRIC_CONTAINER_NUM}.blocc.doc.ic.ac.uk/tls:/var/hyperledger/orderer/tls
        - ~/fabric/orderer.container${FABRIC_CONTAINER_NUM}.blocc.doc.ic.ac.uk:/var/hyperledger/production/orderer
    ports:
      - 7050:7050 # Orderer general listen port
      - 7053:7053 # Orderer admin listen port
      - 9443:9443 # Orderer operations listen port