version: '3.7'
services:
  default:
    container_name: peer0.container${FABRIC_CONTAINER_NUM}.blocc.doc.ic.ac.uk
    image: hyperledger/fabric-peer:latest
    network_mode: host
    labels:
      service: hyperledger-fabric
    environment:
    - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
    - FABRIC_LOGGING_SPEC=DEBUG
    # NOTE: server and client share the same cert and key
    - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
    - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
    - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    - CORE_PEER_PROFILE_ENABLED=false
    # Peer specific variables
    - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
    - CORE_PEER_ADDRESS=0.0.0.0:7051
    #Generic peer variables
    - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
    volumes:
    - ~/fabric/config:/etc/hyperledger/peercfg
    - ~/fabric/organizations/peerOrganizations/container${FABRIC_CONTAINER_NUM}.blocc.doc.ic.ac.uk/peers/peer0.container${FABRIC_CONTAINER_NUM}.blocc.doc.ic.ac.uk:/etc/hyperledger/fabric
    - ~/fabric/peer0.container${FABRIC_CONTAINER_NUM}.blocc.doc.ic.ac.uk:/var/hyperledger/production
    - /var/run:/host/var/run
    working_dir: /root
    command: peer node start
    ports:
    - 7051:7051
    - 9444:9444
