OrdererOrgs:
  - Name: ContainerOrderer5
    Domain: container5.blocc.doc.ic.ac.uk

    Specs:
      - Hostname: orderer
        SANS:
          - blocc-container5.local
          - blocc-container5
          - localhost
          - 127.0.0.1

  - Name: ContainerOrderer6
    Domain: container6.blocc.doc.ic.ac.uk

    Specs:
      - Hostname: orderer
        SANS:
          - blocc-container6.local
          - blocc-container6
          - localhost
          - 127.0.0.1

PeerOrgs:
  - Name: Container5
    Domain: container5.blocc.doc.ic.ac.uk
    EnableNodeOUs: true
    Template:
      Count: 1
      SANS:
        - blocc-container5.local
        - blocc-container5
        - localhost
        - 127.0.0.1
    Users:
      Count: 1

  - Name: Container6
    Domain: container6.blocc.doc.ic.ac.uk
    EnableNodeOUs: true
    Template:
      Count: 1
      SANS:
        - blocc-container6.local
        - blocc-container6
        - localhost
        - 127.0.0.1
    Users:
      Count: 1
